steps:
# Build the container image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/flaskhelloworldapp1-347901/flaskhelloworldapp1', '.']
# Push the container image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/flaskhelloworldapp1-347901/flaskhelloworldapp1']
# Deploy container image to Cloud Run
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args: ['run', 'deploy', 'flaskhelloworldapp1', 'gcr.io/flaskhelloworldapp1-347901/flaskhelloworldapp1@sha256:9bcb58c8ce6db2bfba15b46d35ca938e01827b105b5a716d21ff2a4d8559e451', 'gcr.io/$flaskhelloworldapp1-347901/$flaskhelloworldapp1', '--region', 'us-central1', '--platform', 'managed','--port','80']
images:
- gcr.io/flaskhelloworldapp1-347901/flaskhelloworldapp1